begin;

with rows(slug, title, description) as (
  values
    ('cat-001', 'Audio Gear', 'Curated category placeholder.'),
    ('cat-002', 'AI Assistants', 'Curated category placeholder.'),
    ('cat-003', 'Automation Tools', 'Curated category placeholder.'),
    ('cat-004', 'Analog Synths', 'Curated category placeholder.'),
    ('cat-005', 'Backpacks', 'Curated category placeholder.'),
    ('cat-006', 'Batteries & Power', 'Curated category placeholder.'),
    ('cat-007', 'Blogging Tools', 'Curated category placeholder.'),
    ('cat-008', 'Bluetooth Speakers', 'Curated category placeholder.'),
    ('cat-009', 'Cameras', 'Curated category placeholder.'),
    ('cat-010', 'Creative Suites', 'Curated category placeholder.'),
    ('cat-011', 'Coding IDEs', 'Curated category placeholder.'),
    ('cat-012', 'Cloud Storage', 'Curated category placeholder.'),
    ('cat-013', 'Desk Setups', 'Curated category placeholder.'),
    ('cat-014', 'Drones', 'Curated category placeholder.'),
    ('cat-015', 'Drawing Tablets', 'Curated category placeholder.'),
    ('cat-016', 'DevOps Tools', 'Curated category placeholder.'),
    ('cat-017', 'Editing Suites', 'Curated category placeholder.'),
    ('cat-018', 'E-commerce Tools', 'Curated category placeholder.'),
    ('cat-019', 'Ergonomic Chairs', 'Curated category placeholder.'),
    ('cat-020', 'eReaders', 'Curated category placeholder.'),
    ('cat-021', 'Filmmaking Gear', 'Curated category placeholder.'),
    ('cat-022', 'Fitness Tech', 'Curated category placeholder.'),
    ('cat-023', 'Focus Apps', 'Curated category placeholder.'),
    ('cat-024', 'Field Recorders', 'Curated category placeholder.'),
    ('cat-025', 'Gaming PCs', 'Curated category placeholder.'),
    ('cat-026', 'Graphic Design', 'Curated category placeholder.'),
    ('cat-027', 'Guitars & FX', 'Curated category placeholder.'),
    ('cat-028', 'Green Screens', 'Curated category placeholder.'),
    ('cat-029', 'Home Studios', 'Curated category placeholder.'),
    ('cat-030', 'Headphones', 'Curated category placeholder.'),
    ('cat-031', 'Home Networking', 'Curated category placeholder.'),
    ('cat-032', 'Hardware Kits', 'Curated category placeholder.'),
    ('cat-033', 'iOS Apps', 'Curated category placeholder.'),
    ('cat-034', 'Illustration Tools', 'Curated category placeholder.'),
    ('cat-035', 'Imaging Lenses', 'Curated category placeholder.'),
    ('cat-036', 'IoT Devices', 'Curated category placeholder.'),
    ('cat-037', 'Journaling Apps', 'Curated category placeholder.'),
    ('cat-038', 'Jogging Gear', 'Curated category placeholder.'),
    ('cat-039', 'JavaScript Tooling', 'Curated category placeholder.'),
    ('cat-040', 'Jazz Instruments', 'Curated category placeholder.'),
    ('cat-041', 'Kitchen Tech', 'Curated category placeholder.'),
    ('cat-042', 'Keyboards', 'Curated category placeholder.'),
    ('cat-043', 'Knowledge Bases', 'Curated category placeholder.'),
    ('cat-044', 'KVM Switches', 'Curated category placeholder.'),
    ('cat-045', 'Lighting Kits', 'Curated category placeholder.'),
    ('cat-046', 'Live Streaming', 'Curated category placeholder.'),
    ('cat-047', 'Laptops', 'Curated category placeholder.'),
    ('cat-048', 'Language Tools', 'Curated category placeholder.'),
    ('cat-049', 'Microphones', 'Curated category placeholder.'),
    ('cat-050', 'Mobile Editing', 'Curated category placeholder.'),
    ('cat-051', 'Mechanical Keyboards', 'Curated category placeholder.'),
    ('cat-052', 'Monitors', 'Curated category placeholder.'),
    ('cat-053', 'Noise Reduction', 'Curated category placeholder.'),
    ('cat-054', 'Notetaking Apps', 'Curated category placeholder.'),
    ('cat-055', 'NAS Storage', 'Curated category placeholder.'),
    ('cat-056', 'Networking Tools', 'Curated category placeholder.'),
    ('cat-057', 'Office Essentials', 'Curated category placeholder.'),
    ('cat-058', 'Open Source Kits', 'Curated category placeholder.'),
    ('cat-059', 'On-camera Lighting', 'Curated category placeholder.'),
    ('cat-060', 'Outdoor Audio', 'Curated category placeholder.'),
    ('cat-061', 'Photography', 'Curated category placeholder.'),
    ('cat-062', 'PC Builds', 'Curated category placeholder.'),
    ('cat-063', 'Podcasting', 'Curated category placeholder.'),
    ('cat-064', 'Productivity Suites', 'Curated category placeholder.'),
    ('cat-065', 'Quick Chargers', 'Curated category placeholder.'),
    ('cat-066', 'Quantum Laptops', 'Curated category placeholder.'),
    ('cat-067', 'QA Tooling', 'Curated category placeholder.'),
    ('cat-068', 'Recording Interfaces', 'Curated category placeholder.'),
    ('cat-069', 'Render Farms', 'Curated category placeholder.'),
    ('cat-070', 'Remote Work', 'Curated category placeholder.'),
    ('cat-071', 'Router Setups', 'Curated category placeholder.'),
    ('cat-072', 'Studio Desks', 'Curated category placeholder.'),
    ('cat-073', 'Smart Home', 'Curated category placeholder.'),
    ('cat-074', 'Security Tools', 'Curated category placeholder.'),
    ('cat-075', 'Sound Design', 'Curated category placeholder.'),
    ('cat-076', 'Tech Tools', 'Curated category placeholder.'),
    ('cat-077', 'Tablets', 'Curated category placeholder.'),
    ('cat-078', 'Travel Gear', 'Curated category placeholder.'),
    ('cat-079', 'Typography Kits', 'Curated category placeholder.'),
    ('cat-080', 'USB Accessories', 'Curated category placeholder.'),
    ('cat-081', 'UI Kits', 'Curated category placeholder.'),
    ('cat-082', 'Ultrabooks', 'Curated category placeholder.'),
    ('cat-083', 'UPS Backup', 'Curated category placeholder.'),
    ('cat-084', 'Video Editing', 'Curated category placeholder.'),
    ('cat-085', 'VR Headsets', 'Curated category placeholder.'),
    ('cat-086', 'Voice Assistants', 'Curated category placeholder.'),
    ('cat-087', 'Virtual Studios', 'Curated category placeholder.'),
    ('cat-088', 'Web Apps', 'Curated category placeholder.'),
    ('cat-089', 'Wearables', 'Curated category placeholder.'),
    ('cat-090', 'Wireless Mics', 'Curated category placeholder.'),
    ('cat-091', 'Workspace Decor', 'Curated category placeholder.'),
    ('cat-092', 'XLR Gear', 'Curated category placeholder.'),
    ('cat-093', 'Xcode Tooling', 'Curated category placeholder.'),
    ('cat-094', 'XR Devices', 'Curated category placeholder.'),
    ('cat-095', 'YouTube Kits', 'Curated category placeholder.'),
    ('cat-096', 'Yarn Tooling', 'Curated category placeholder.'),
    ('cat-097', 'Yoga Tech', 'Curated category placeholder.'),
    ('cat-098', 'Zoom Rooms', 'Curated category placeholder.'),
    ('cat-099', 'Zippers & Cases', 'Curated category placeholder.'),
    ('cat-100', 'Zen Workflows', 'Curated category placeholder.')
),
owner as (
  select id from auth.users where email = 'rahulb1407@gmail.com' limit 1
)
insert into public.categories (slug, title, description, is_active, created_by)
select
  rows.slug,
  rows.title,
  rows.description,
  true,
  owner.id
from rows
left join owner on true
on conflict (slug) do update
set
  title = excluded.title,
  description = excluded.description,
  is_active = true;

commit;
