begin;

with rows(slug, title, description) as (
  values
    ('cat-001', 'Audio Gear', 'Interfaces, mixers, headphones, and recording tools for clean sound setups.'),
    ('cat-002', 'AI Assistants', 'Chat, writing, coding, and research assistants that accelerate daily work.'),
    ('cat-003', 'Automation Tools', 'Workflow builders, triggers, and scripts that remove repetitive manual tasks.'),
    ('cat-004', 'Analog Synths', 'Hardware synths, sequencers, and modular tools for tactile sound design.'),
    ('cat-005', 'Backpacks', 'Carry systems, camera bags, and everyday packs for gear-heavy travel.'),
    ('cat-006', 'Batteries & Power', 'Chargers, battery packs, and power management gear for reliable uptime.'),
    ('cat-007', 'Blogging Tools', 'Writing, publishing, SEO, and editorial tools for running content sites.'),
    ('cat-008', 'Bluetooth Speakers', 'Portable and desktop speakers for casual listening or mobile playback.'),
    ('cat-009', 'Cameras', 'Mirrorless, DSLR, compact, and creator-first cameras for photo and video.'),
    ('cat-010', 'Creative Suites', 'Full software suites for design, motion, editing, and creative production.'),
    ('cat-011', 'Coding IDEs', 'Editors and integrated environments for shipping software faster.'),
    ('cat-012', 'Cloud Storage', 'Sync, backup, and asset-sharing services for files across teams and devices.'),
    ('cat-013', 'Desk Setups', 'Desks, peripherals, lighting, and layout ideas for productive workspaces.'),
    ('cat-014', 'Drones', 'Flying cameras, controllers, and accessories for aerial shooting and scouting.'),
    ('cat-015', 'Drawing Tablets', 'Pen displays and tablets for illustration, retouching, and digital art.'),
    ('cat-016', 'DevOps Tools', 'Deployment, monitoring, CI, and infrastructure tooling for modern teams.'),
    ('cat-017', 'Editing Suites', 'Post-production tools for cutting, color, audio cleanup, and delivery.'),
    ('cat-018', 'E-commerce Tools', 'Storefront, operations, and conversion tools for selling online.'),
    ('cat-019', 'Ergonomic Chairs', 'Supportive seating for long editing, gaming, and coding sessions.'),
    ('cat-020', 'eReaders', 'Dedicated reading devices and accessories for focused digital reading.'),
    ('cat-021', 'Filmmaking Gear', 'Production gear for shooting, rigging, monitoring, and directing scenes.'),
    ('cat-022', 'Fitness Tech', 'Wearables, sensors, and recovery tools for training and health tracking.'),
    ('cat-023', 'Focus Apps', 'Timers, blockers, and habit tools that reduce distraction and improve output.'),
    ('cat-024', 'Field Recorders', 'Portable recorders and audio capture tools for on-location sound.'),
    ('cat-025', 'Gaming PCs', 'Prebuilts and custom towers optimized for performance-heavy gaming rigs.'),
    ('cat-026', 'Graphic Design', 'Branding, layout, and asset tools for visual design workflows.'),
    ('cat-027', 'Guitars & FX', 'Electric guitars, pedals, amps, and effect chains for recording or stage.'),
    ('cat-028', 'Green Screens', 'Background kits and compositing gear for virtual sets and keying.'),
    ('cat-029', 'Home Studios', 'Compact production spaces with the essentials for recording at home.'),
    ('cat-030', 'Headphones', 'Monitoring, travel, and casual headphones across wired and wireless setups.'),
    ('cat-031', 'Home Networking', 'Routers, mesh systems, and networking gear for stable connected homes.'),
    ('cat-032', 'Hardware Kits', 'Repair, prototyping, and electronics kits for hands-on technical work.'),
    ('cat-033', 'iOS Apps', 'Mobile apps for creators, operators, and everyday productivity on iPhone and iPad.'),
    ('cat-034', 'Illustration Tools', 'Brushes, software, and reference tools for illustration workflows.'),
    ('cat-035', 'Imaging Lenses', 'Prime, zoom, and specialty lenses for sharper visual storytelling.'),
    ('cat-036', 'IoT Devices', 'Connected hardware for automation, sensing, control, and remote monitoring.'),
    ('cat-037', 'Journaling Apps', 'Private writing and reflection tools for notes, logs, and thinking.'),
    ('cat-038', 'Jogging Gear', 'Running accessories, wearables, and carry gear for active routines.'),
    ('cat-039', 'JavaScript Tooling', 'Frameworks, runtimes, and utilities that shape JS development stacks.'),
    ('cat-040', 'Jazz Instruments', 'Instruments and accessories tailored to jazz performance and practice.'),
    ('cat-041', 'Kitchen Tech', 'Appliances, gadgets, and workflow tools for modern cooking setups.'),
    ('cat-042', 'Keyboards', 'Typing keyboards for work, gaming, portability, or desk aesthetics.'),
    ('cat-043', 'Knowledge Bases', 'Docs, wikis, and reference systems for teams and solo operators.'),
    ('cat-044', 'KVM Switches', 'Hardware that makes multi-computer desk setups easier to control.'),
    ('cat-045', 'Lighting Kits', 'Lights, modifiers, and stands for studio, desk, or content production.'),
    ('cat-046', 'Live Streaming', 'Cameras, switchers, capture gear, and software for live broadcasts.'),
    ('cat-047', 'Laptops', 'Portable computers for editing, design, software, and remote work.'),
    ('cat-048', 'Language Tools', 'Translation, writing, and learning tools for multilingual workflows.'),
    ('cat-049', 'Microphones', 'Mics and supporting gear for voice, podcast, music, and streaming.'),
    ('cat-050', 'Mobile Editing', 'Apps and accessories for editing video, photo, and audio on the go.'),
    ('cat-051', 'Mechanical Keyboards', 'Mechanical boards, switches, and custom builds for refined typing feel.'),
    ('cat-052', 'Monitors', 'Displays for color work, coding, gaming, and multi-screen setups.'),
    ('cat-053', 'Noise Reduction', 'Software and hardware that reduce hiss, rumble, and room noise.'),
    ('cat-054', 'Notetaking Apps', 'Capture, organize, and retrieve notes across work and personal systems.'),
    ('cat-055', 'NAS Storage', 'Local network storage for backups, archives, media libraries, and teams.'),
    ('cat-056', 'Networking Tools', 'Diagnostics, cabling, and support tools for network troubleshooting.'),
    ('cat-057', 'Office Essentials', 'Core gear and supplies that keep everyday work moving smoothly.'),
    ('cat-058', 'Open Source Kits', 'Open source stacks, templates, and self-hosted tools worth adopting.'),
    ('cat-059', 'On-camera Lighting', 'Compact lights and modifiers designed to travel with the camera.'),
    ('cat-060', 'Outdoor Audio', 'Portable speakers, recorders, and rugged audio gear for outside use.'),
    ('cat-061', 'Photography', 'Camera systems, lighting, and support gear for still-image workflows.'),
    ('cat-062', 'PC Builds', 'Custom desktop parts and completed builds for work or play.'),
    ('cat-063', 'Podcasting', 'Recording, publishing, and monitoring gear for podcast production.'),
    ('cat-064', 'Productivity Suites', 'Integrated work suites for communication, docs, planning, and execution.'),
    ('cat-065', 'Quick Chargers', 'Fast-charging bricks, cables, and power accessories for busy setups.'),
    ('cat-066', 'Quantum Laptops', 'Experimental or high-end laptop setups pushing performance and mobility.'),
    ('cat-067', 'QA Tooling', 'Testing, bug tracking, and release confidence tools for product teams.'),
    ('cat-068', 'Recording Interfaces', 'Audio interfaces and I/O gear for tracking music and voice.'),
    ('cat-069', 'Render Farms', 'Distributed render tools and services for heavy visual workloads.'),
    ('cat-070', 'Remote Work', 'Home-office tools and routines that make remote collaboration smoother.'),
    ('cat-071', 'Router Setups', 'Router-centric setups for speed, coverage, and network control.'),
    ('cat-072', 'Studio Desks', 'Purpose-built desks and furniture for production-heavy workspaces.'),
    ('cat-073', 'Smart Home', 'Connected home devices for comfort, automation, and remote control.'),
    ('cat-074', 'Security Tools', 'Digital and physical tools for privacy, security, and safe access.'),
    ('cat-075', 'Sound Design', 'Plugins, libraries, and hardware for shaping distinctive sonic textures.'),
    ('cat-076', 'Tech Tools', 'General-purpose creator and operator tools that earn a permanent slot.'),
    ('cat-077', 'Tablets', 'Tablet computers and accessories for sketching, reading, and mobile work.'),
    ('cat-078', 'Travel Gear', 'Portable essentials for working, filming, or creating while traveling.'),
    ('cat-079', 'Typography Kits', 'Font libraries, layout tools, and resources for type-driven design.'),
    ('cat-080', 'USB Accessories', 'Hubs, docks, adapters, and small accessories that expand device utility.'),
    ('cat-081', 'UI Kits', 'Design systems, component kits, and assets for interface work.'),
    ('cat-082', 'Ultrabooks', 'Thin, lightweight laptops built for travel and high-mobility work.'),
    ('cat-083', 'UPS Backup', 'Battery backup and surge protection for downtime-sensitive setups.'),
    ('cat-084', 'Video Editing', 'Editors, plugins, and supporting gear for polished video post workflows.'),
    ('cat-085', 'VR Headsets', 'Virtual reality headsets and accessories for immersive experiences.'),
    ('cat-086', 'Voice Assistants', 'Voice-controlled devices and services for hands-free automation.'),
    ('cat-087', 'Virtual Studios', 'Software and hardware that simulate or extend studio production spaces.'),
    ('cat-088', 'Web Apps', 'Browser-based tools for creators, teams, and digital operators.'),
    ('cat-089', 'Wearables', 'Smart watches, bands, and sensors that stay with you all day.'),
    ('cat-090', 'Wireless Mics', 'Cable-free microphone systems for interviews, streaming, and video.'),
    ('cat-091', 'Workspace Decor', 'Objects and accents that make a workspace feel intentional and usable.'),
    ('cat-092', 'XLR Gear', 'Microphones, cables, interfaces, and accessories built around XLR audio.'),
    ('cat-093', 'Xcode Tooling', 'Apple-platform development tools, utilities, and debugging helpers.'),
    ('cat-094', 'XR Devices', 'Mixed reality and extended reality devices for spatial workflows.'),
    ('cat-095', 'YouTube Kits', 'Starter and advanced gear stacks for producing YouTube content.'),
    ('cat-096', 'Yarn Tooling', 'Tooling, package workflows, and utilities centered on Yarn projects.'),
    ('cat-097', 'Yoga Tech', 'Apps, wearables, and accessories that support mindful movement routines.'),
    ('cat-098', 'Zoom Rooms', 'Hardware and software setups for polished video meeting spaces.'),
    ('cat-099', 'Zippers & Cases', 'Cases, organizers, and protective storage for small gear and cables.'),
    ('cat-100', 'Zen Workflows', 'Calm, minimal tools and routines designed for focused workdays.')
),
owner as (
  select id from auth.users where email = 'rahulb1407@gmail.com' limit 1
)
insert into public.categories (slug, title, description, is_active, created_by)
select
  rows.slug,
  rows.title,
  rows.description,
  true,
  owner.id
from rows
left join owner on true
on conflict (slug) do update
set
  title = excluded.title,
  description = excluded.description,
  is_active = true;

commit;
